version: '3.9'


volumes:
  pg_data:
  redis_data:

services:

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file: ../src/core/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always

  fastapi:
    container_name: fastapi
    build: ../src
    env_file:
      - ../src/core/.env
    restart: unless-stopped
    expose:
      - "8000"

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
      - postgres