version: '3.9'

volumes:
  pg_data:

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file: ../src/core/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
