version: '3.9'

volumes:
  pg_data:
  redis_data:

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file: ../src/core/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
